---
spring:
  profiles: peer1
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    hostname: peer1
  client:
    service-url:
      defaultZone:  http://peer2:8081/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: peer2
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address:  true
    hostname: peer2
  client:
    service-url:
      defaultZone:  http://peer1:8080/eureka/
    register-with-eureka: false
    fetch-registry: false