
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jianghh1993/learning-springcloud-config
          username: jianghh1993
          password: qaz1993217
          search-paths: config
          default-label: master
  application:
    name: config-server
  profiles:
    active: remote
server:
  port: 8769